name: booking_hotel
description: Initium Solutions Task.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.2
  animated_text_kit: ^4.2.1
  get: ^4.6.1
  shared_preferences: ^2.0.13
  flutter_bloc: ^8.0.1
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  sqflite: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

